name: Katalon Test

on:
  workflow_dispatch:

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Katalon Studio
      uses: katalon-studio/katalon-studio-docker@v1.0.0
      with:
        version: '7.9.1'

    - name: Run Katalon Studio tests
      run: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Fiture Product.groovy"
